# Generated by Django 2.2.5 on 2019-09-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todoitem_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='cotent',
            new_name='content',
        ),
    ]
