# Generated by Django 2.2.5 on 2019-09-07 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190907_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='date',
            field=models.DateField(default=datetime.date(2019, 9, 7)),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
    ]
