# Generated by Django 2.2.5 on 2019-09-07 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190907_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 9, 7, 16, 48, 42, 72810)),
        ),
    ]
