# Generated by Django 2.2.5 on 2019-09-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20190908_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
