# Generated by Django 2.2.5 on 2019-09-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20190908_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='task_id',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
